<?php

namespace Santa\CoolSchoolBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpecializationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecializationRepository extends EntityRepository
{
}
